In [1]:
grid=[[6,1,0, 0,0,0, 0,0,0],
      [0,0,0, 0,4,3, 0,0,0],
      [7,0,0, 0,0,0, 0,5,6],
      
      [0,0,1, 9,0,0, 2,0,0],
      [0,0,0, 5,3,4, 0,0,0],
      [0,0,4, 0,0,2, 8,0,0],
      
      [5,7,0, 3,0,7, 6,0,0],
      [3,0,0, 2,0,4, 0,0,1],
      [0,2,0, 0,6,0, 0,4,0]]

In [2]:
import numpy as np

def possible(y,x,n):
    global grid
    for i in range(9):
        if grid[y][i]==n:
            return False
    for i in range(9):
        if grid[i][x]==n:
            return False
    x0=(x//3)*3
    y0=(y//3)*3
    for i in range(3):
        for j in range(3):
            if grid[y0+i][x0+j]==n:
                return False
    return True

In [3]:
def solve():
    global grid
    for y in range(9):
        for x in range(9):
            if grid[y][x]==0:
                for n in range(1,10):
                    if possible(y,x,n):
                        grid[y][x]=n
                        solve()
                        grid[y][x]=0
                return
    print(np.matrix(grid))

In [4]:
solve()

[[9 8 4 7 2 6 5 1 3]
 [5 6 1 9 4 3 8 7 2]
 [2 3 7 5 8 1 4 6 9]
 [7 5 2 4 9 8 1 3 6]
 [8 1 9 6 3 2 7 5 4]
 [6 4 3 1 7 5 2 9 8]
 [4 9 8 3 1 7 6 2 5]
 [3 7 6 2 5 4 9 8 1]
 [1 2 5 8 6 9 3 4 7]]
